### PR TITLE
Add common string functions

### PR DESCRIPTION
**Pull request by gomes**
Adding common string functions to improve the template creation.

### CODE REVIEW

**Comment by alexanderjardim** [comment]
@gomes , I think you should fix the broken lib dependency so this PR can go on.

**Comment by activars** [comment]
Do you mind write a very small string test for this?

This should be easier comparing to the integration test.

**Comment by gomes** [comment]
@alexanderjardim I did the fix in the 2º commit
@activars I already did that, please check

**Comment by activars** [comment]
awesome! Thumbs up!

**Comment by nickpoorman** [comment]
I'm trying to turn `/nginx` into `nginx` and for some reason I all of the following are producing `::nginx`.

didn't work:

```
        # This is the default proxy criteria
        acl {{ $app.EscapedId }}-aclrule hdr(host) -i {{ Replace $app.Id "/" "" 1 }}
        use_backend {{ $app.EscapedId }}-cluster if {{ $app.EscapedId }}-aclrule
        {{ end }} {{ end }}
```

didn't work:

```
        # This is the default proxy criteria
        acl {{ $app.EscapedId }}-aclrule hdr(host) -i {{ Replace $app.EscapedId "/" "" 1 }}
        use_backend {{ $app.EscapedId }}-cluster if {{ $app.EscapedId }}-aclrule
        {{ end }} {{ end }}
```

I even tried replacing the `::` and it didn't work:

didn't work:

```
        # This is the default proxy criteria
        acl {{ $app.EscapedId }}-aclrule hdr(host) -i {{ Replace $app.Id "::" "" 1 }}
        use_backend {{ $app.EscapedId }}-cluster if {{ $app.EscapedId }}-aclrule
        {{ end }} {{ end }}
```

didn't work:

```
        # This is the default proxy criteria
        acl {{ $app.EscapedId }}-aclrule hdr(host) -i {{ Replace $app.EscapedId "::" "" 1 }}
        use_backend {{ $app.EscapedId }}-cluster if {{ $app.EscapedId }}-aclrule
        {{ end }} {{ end }}
```

What can I do to have the `/` stripped out of from the beginning of: `/nginx`?

**Pull request merged**
