### PR TITLE
Move package dependencies to the Godep directory

### PR DESCRIPTION
**Pull request by activars**
This helps building consistent packages. No need to run `godep restore`. 

TODOs
[-] Fix build & packaging process
[-] Fix travis
[-] Fix jenkins script
[-] Fix Docker build
[-] Cleanup commits messages

### CODE REVIEW

**Comment by xiaods** [comment]
LGTM

**Comment by activars** [comment]
@xiaods :)
I need to find time run through some integration test...

**Comment by activars** [comment]
being prompt to master branch soon.

**Comment by activars** [comment]
Hopefully this should cover most of changes, if you see issues pls submit PR or issue.

**Pull request merged**
