### PR TITLE
Expose marathon labels and health checks

### PR DESCRIPTION
**Pull request by lclarkmichalek**
Marathon now has the ability to add labels to an app; these allow passing metadata somewhere other than environment variables. Also expose a full health check object to enable better multiport health checking.

Also ran go fmt over the codebase which is why there are so many files changed

### CODE REVIEW

**Comment by activars** [comment]
lgtm, @pdpi can you take a look as well?

**Comment by pdpi** [comment]
Was already on it

**Comment by pdpi** [comment]
:ship: it.

**Comment by timoreimann** [comment]
Great feature!

I'd suggest though we separate code style changes from functional changes in the future. This way, it's easier to see what functional part has actually been added, changed, or removed.

**Comment by lclarkmichalek** [comment]
100% correct; I just don't like making style pull requests without making
some kind of contribution to the project first (and no way was I commiting
without running gofmt) ;) But yes, mea culpa on that count

On 19 June 2015 at 15:13, Timo Reimann <notifications@github.com> wrote:

> Great feature!
>
> I'd suggest though we separate code style changes from functional changes
> in the future. This way, it's easier to see what functional part has
> actually been added, changed, or removed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QubitProducts/bamboo/pull/138#issuecomment-113527305>.
>



-- 
Laurie Clark-Michalek
Infrastructure Engineer


Qubit

20 Broadwick Street

London

W1F 8HT


Website: www.qubit.com <http://www.qubitproducts.com/>


Qubit - Real Insights. Real Uplifts.


This email may be confidential or privileged. If you received this
communication by mistake, please don't forward it to anyone else, please
erase all copies and attachments, and please let me know that it has gone
to the wrong person. Thanks.

**Pull request merged**
