### PR TITLE
Reload rework

### PR DESCRIPTION
**Pull request by bluepeppers**
Reworks most of the HAProxy reloading code to be a little more testable (and adds tests), while keeping the logic mostly identical. Also adds the features in #158.

The major affect of all this is that
 - We no longer exit if there is a problem trying to reload the haproxy config
 - We have better logging in the area
  - The names of the statsd metrics were changed (well, I added a 2 and changed 1)
 - We have a nice reliable way to test and cleanup config reloads.

Checklist:
 - [x] Test
 - [x] Document
 - [x] Test on staging cluster for a while

### CODE REVIEW

**Comment by activars** [comment]
Do you mind squash the commits to sensible group?
[ ] Update README.md
[ ] Update example/dev config

**Comment by bluepeppers** [comment]
Done

**Comment by activars** [comment]
looks good :+1:  let's test on staging before release.

**Comment by bluepeppers** [comment]
Seems hunky dory on staging. Merging and deploying.

**Pull request merged**
