### PR TITLE
Update to ubuntu 15.10

### PR DESCRIPTION
**Pull request by imshashank**
Update to get new golang

Fixes the bug when building the docker image.

```
Step 9 : RUN go get github.com/tools/godep &&     go get -t github.com/smartystreets/goconvey &&     go build &&     ln -s /opt/go/src/github.com/QubitProducts/bamboo /var/bamboo &&     mkdir -p /run/haproxy &&     mkdir -p /var/log/supervisor
 ---> Running in 4f034c6ddb5a

# github.com/QubitProducts/bamboo

./bamboo.go:185: client.Timeout undefined (type *http.Client has no field or method Timeout)

The command '/bin/sh -c go get github.com/tools/godep &&     go get -t github.com/smartystreets/goconvey &&     go build &&     ln -s /opt/go/src/github.com/QubitProducts/bamboo /var/bamboo &&     mkdir -p /run/haproxy &&     mkdir -p /var/log/supervisor' returned a non-zero code: 2
```

### CODE REVIEW

**Comment by imshashank** [comment]
Fixes the bug https://github.com/QubitProducts/bamboo/pull/193

**Comment by activars** [comment]
Thank you for PR. We usually recommend using Ubuntu LTS releases for the build.
I can see there's a need to build on 15.10.  It might make sense to create a separate Dockerfile for another Docker build.

**Comment by bluepeppers** [comment]
I'm pretty OK with this, seeing as 16.04 is just around the corner, and we can update to LTS then. Another option might be using godeb to install a specific go version, or using the official golang image.

**Comment by imshashank** [comment]
It makes sense to change this to 15.10 from 14.04 instead of creating a new file as the docker image did not get build at all. So the Dockerfile is kind of broken.

**Comment by activars** [comment]
Thank you.

**Pull request merged**
