### PR TITLE
add ipAddress to support docker network like macvlan

### PR DESCRIPTION
**Pull request by Willbern**
When  craeting an app with with docker macvlan network in marathon，there is two steps we may do bellow:  reference: https://docs.docker.com/engine/userguide/networking/get-started-macvlan/

1. create docker macvlan network

      	docker network create -d macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 --ip-range=192.168.1.128/28 -o parent=eth0 -o macvlan_mode=bridge macvlan0
      
2. deploy an app with json

       {
  		"id": "macvlan-2048",
  		"cmd": null,
  		"cpus": 0.1,
  		"mem": 128,
  		"disk": 0,
  		"instances": 1,
  		"container": {
    	"docker": {
      		"image": "",
      		"network": "HOST",
      		"parameters": [
		{
          "key": "net",
          "value": "macvlan0"
        }
        ]
    	},
    	"type": "DOCKER"
  		},
  		"ipAddress":{
			"discovery":{
				"ports":[
		    		{
					"number":80,
					"name":"http",
					"protocol":"tcp"
		    		}
					]
				}
  			}
		}
		
this PR add IpAddress field and update the createApps function to support app with macvlan network

### CODE REVIEW

**Comment by activars** [comment]
Thanks for the PR. @Willbern would you be able to resolve the git conflicts?

**Comment by Willbern** [comment]
@activars ok

**Comment by Willbern** [comment]
@activars Thanks for your review. I had resolve the git conflicts and add some unit test, but how to trigger the checks to run again  manually?

**Comment by activars** [comment]
Your commit triggers the test automatically.

**Comment by Willbern** [comment]
@activars i have update the commit, but it does't run yet

**Comment by activars** [comment]
There might be a test queue, I think it just managed to run and passed the test.

**Comment by Willbern** [comment]
Yeah, the test passed and thanks for your reply.

**Pull request merged**
