### PR TITLE
Marathon apps can have multiple service ports

### LINKED ISSUE #54: bamboo not using service ports
I think current bamboo implementation does not take into account tasks service port(s). 

Let me demonstrate it on one example with 2 exposed service ports:
Lets say I have following marathon app:
```
{
    "id": "marattest-dev",
    "cmd": "curl -q -o /app.py https://gist.githubusercontent.com/veverjak/b8607526f071f296bd8c/raw/3545a22d421d1f041ca5a8b305ea00f7edf967c6/get_file_content.py && python /app.py /etc/ip",
    "instances": 3,
    "cpus": 0.1,
    "mem": 10,
    "constraints": [],
    "uris": ["/.dockercfg"],
    "taskRateLimit": 1,
    "container": {
      "type": "DOCKER",
      "volumes": [
            {
                "containerPath": "/var/lib/scripts/create_configs.sh",
                "hostPath": "/var/lib/scripts/create_configs.sh",
                "mode": "RO"
            },
            {
                "containerPath": "/usr/bin/etcdctl",
                "hostPath": "/usr/bin/etcdctl",
                "mode": "RO"
            },
            {
                "containerPath": "/etc/ip",
                "hostPath": "/etc/ip",
                "mode": "RO"
            }
      ],
      "docker": {
        "image": "quay.io/appuri/get_file_content",
        "portMappings": [
          { "containerPort": 5000, "hostPort": 0, "servicePort": 9001, "protocol": "tcp" },
          { "containerPort": 5001, "hostPort": 0, "servicePort": 9002, "protocol": "tcp" }

        ],
        "network": "BRIDGE"
      }
    }
}
```

result for /v2/tasks gives:
```
{
  "tasks": [
    {
      "appId": "/marattest-dev",
      "id": "marattest-dev.46b9ab9c-6738-11e4-b85e-1645b8de8fb1",
      "host": "ip-10-0-1-151.us-west-2.compute.internal",
      "ports": [
        31003,
        31004
      ],
      "startedAt": "2014-11-08T11:38:08.063Z",
      "stagedAt": "2014-11-08T11:13:33.038Z",
      "version": "2014-11-08T11:13:29.557Z",
      "servicePorts": [
        9001,
        9002
      ]
    },
    {
      "appId": "/marattest-dev",
      "id": "marattest-dev.c2f5c97a-6736-11e4-b85e-1645b8de8fb1",
      "host": "ip-10-0-1-149.us-west-2.compute.internal",
      "ports": [
        31006,
        31007
      ],
      "startedAt": "2014-11-08T11:38:08.051Z",
      "stagedAt": "2014-11-08T11:02:42.474Z",
      "version": "2014-11-08T11:02:39.555Z",
      "servicePorts": [
        9001,
        9002
      ]
    },
    {
      "appId": "/marattest-dev",
      "id": "marattest-dev.4752421f-6738-11e4-b85e-1645b8de8fb1",
      "host": "ip-10-0-1-149.us-west-2.compute.internal",
      "ports": [
        31008,
        31009
      ],
      "startedAt": "2014-11-08T11:38:08.022Z",
      "stagedAt": "2014-11-08T11:13:34.037Z",
      "version": "2014-11-08T11:13:29.557Z",
      "servicePorts": [
        9001,
        9002
      ]
    },
```

If I am using [default marathon bash script](https://github.com/mesosphere/marathon/blob/master/bin/haproxy-marathon-bridge) to create haproxy.cfg, I get:
```
listen marattest-dev-9001
  bind 0.0.0.0:9001
  mode tcp
  option tcplog
  balance leastconn
  server marattest-dev-3 ip-10-0-1-151.us-west-2.compute.internal:31003 check
  server marattest-dev-2 ip-10-0-1-149.us-west-2.compute.internal:31006 check
  server marattest-dev-1 ip-10-0-1-149.us-west-2.compute.internal:31008 check

listen marattest-dev-9002
  bind 0.0.0.0:9002
  mode tcp
  option tcplog
  balance leastconn
  server marattest-dev-3 ip-10-0-1-151.us-west-2.compute.internal:31004 check
  server marattest-dev-2 ip-10-0-1-149.us-west-2.compute.internal:31007 check
  server marattest-dev-1 ip-10-0-1-149.us-west-2.compute.internal:31009 check
```

If I want the same from bamboo, it generates:
```
## listen ::marattest-dev_0
##   bind *:0
##   mode http
##
##   balance leastconn
##   option forwardfor
##
##         server ::marattest-dev-ip-10-0-1-149.us-west-2.compute.internal-31006 ip-10-0-1-149.us-west-2.compute.internal:31006
##         server ::marattest-dev-ip-10-0-1-151.us-west-2.compute.internal-31003 ip-10-0-1-151.us-west-2.compute.internal:31003
##         server ::marattest-dev-ip-10-0-1-149.us-west-2.compute.internal-31008 ip-10-0-1-149.us-west-2.compute.internal:31008
#
```

It is because listen endpoint is created only per app and first [app port is considered to be the only service port](https://github.com/QubitProducts/bamboo/blob/master/services/marathon/marathon.go#L179) which I didn't define because I expected same behavior like default bash script has.

Workaround for me will be defining `ports: []` per app and use only one port, which is fine for now, but I believe this can be easily fixed by adding proper structure in [Create Apps](https://github.com/QubitProducts/bamboo/blob/master/services/marathon/marathon.go#L150).

### PR DESCRIPTION
**Pull request by MiLk**
Fixes #54 
Replaces #84 

You can have apps which listen on different ports (nginx with 80 and 443), and each task will also have two ports.
screen shot 2015-03-26 at 7 15 04 pm

#84 doesn't map the app ports to the right task ports.

### CODE REVIEW

**Comment by activars** [comment]
Thanks for the PR, I have to review this together with the user interface & API changes.

**Comment by hyper-carrot** [comment]
I need it eagerly! Please speed up this process. Thanks.

**Comment by timoreimann** [comment]
@activars What's keeping us from merging this PR exactly? The feature looks pretty useful and is small enough so that it could be refactored fairly easily once the project aims for something bigger. Also, the changes are just implementation details, so there's no public API that could be broken. (Except for the template maybe, but I personally do not consider that to be part of any API.)

**Comment by activars** [comment]
Thank you for the suggestion, I think that's valid concern.
I will test very soon this week. If there's no major backwards compatibility breakage, I will merge (expect a release soon)

**Comment by timoreimann** [comment]
Sounds good. Thanks!

**Comment by kikito** [comment]
:+1:

**Comment by activars** [comment]
I had a look and tested it locally, I see a couple of issues here. 
- I would like to allow bamboo to overrides the random assigned hosted port by Marathon. If I'm correct, marathon would not allow 443 to be used multiple times.
- It's missing TCP use cases (this one should be easy to fix)

Looks like this is most wanted feature, I'm working on a branch that has:
- A REST endpoint so you can override the service ports
- Otherwise keep the default one that marathon offers (random or preconfigured)
- UI to allow configure this change
- Some backward compatibility (likely to break a little)

**Comment by MiLk** [comment]
To support TCP, what about:
```
{{ range $index, $app := .Apps }}
    {{ range $serviceIndex, $servicePort := $app.ServicePorts }}
        {{ if ne $app.Env.BAMBOO_IS_HTTP 1 }}
listen {{ $app.EscapedId }}_{{ $servicePort }}
        bind *:{{ $servicePort }}
        mode tcp
        option tcplog
        balance leastconn

            {{ range $page, $task := $app.Tasks }}
        server {{ $app.EscapedId }}-{{ $task.Host }}-{{ index $task.Ports $serviceIndex }} {{ $task.Host }}:{{ index $task.Ports $serviceIndex }}
            {{ end }}
        {{ end }}
    {{ end }}
{{ end }}

{{ range $index, $app := .Apps }}
  {{ range $serviceIndex, $servicePort := $app.ServicePorts }}
    {{ if eq $app.Env.BAMBOO_IS_HTTP 1 }}
 listen {{ $app.EscapedId }}_{{ $servicePort }}
   bind *:{{ $servicePort }}
   mode http
   {{ if $app.HealthCheckPath }}
     option httpchk GET {{ $app.HealthCheckPath }}
   {{ end }}
   balance leastconn
   option forwardfor
         {{ range $page, $task := $app.Tasks }}
         server {{ $app.EscapedId }}-{{ $task.Host }}-{{ index $task.Por    ts $serviceIndex }} {{ $task.Host }}:{{ index $task.Ports $serviceIndex }}     {{ if $app.HealthCheckPath }} check inter 30000 {{ end }} {{ end }}
     {{ end }}
   {{ end }}
 {{ end }}
```
About the fact we can't use 443 or 80 multiple times, it's something introduced with marathon 0.8.1, and I didn't have solved this problem on my infrastructure. We are still on 0.8.0 at the time being.

**Comment by timoreimann** [comment]
@activars, what's the state on this one? I'm fairly eager to use this feature, so I am wondering if there is a way to split the effort into smaller chunks. To me it seems worth considering to pass the PR without the additional features you proposed (port overriding, REST endpoint, UI) as long as configuration can be managed via the template, and follow up with another PR once things are done.

What do you think?

**Comment by MiLk** [comment]
My PR only adds two new variables, so it's totally safe to merge it and implement the other features at a later time.

**Comment by timoreimann** [comment]
@activars, what are your thoughts regarding @MiLk's latest comment?

**Comment by activars** [comment]
Hey, I'm looking into merging it today.
I want to make bigger change to the project, but it might take longer so
I'm considering merging this avoid blocking you guys.


On 8 May 2015, at 08:04, Timo Reimann <notifications@github.com> wrote:

@activars <https://github.com/activars>, what are your thoughts regarding
@MiLk <https://github.com/MiLk>'s latest comment?

—
Reply to this email directly or view it on GitHub
<https://github.com/QubitProducts/bamboo/pull/96#issuecomment-100128475>.

**Comment by activars** [comment]
apologise for the late reply, I think it's ok to merge. Thanks for the contribution.

**Comment by MiLk** [comment]
Thanks :dancers:

**Pull request merged**
